---
title: Bombe de fête
hero_image: images/banner.png
description:
  - Fabriquer une bombe de fête réutilisable qui te récompense avec un affichage lumineux et sonore lorsqu'elle est tirée
  - s'affiche lorsqu'il est tiré
meta_title: Projets Raspberry Pi Pico | Bombe de fête
meta_description: Un projet Raspberry Pi Pico pour fabriquer une bombe de table réutilisable qui te récompensera avec un affichage lumineux et sonore lorsqu'il sera tiré.
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: Ce que tu vas faire
  - 
    title: Allumer ta LED RVB
  - 
    title: Faire du bruit
    completion:
      - engaged
  - 
    title: Activer ta bombe de fête
  - 
    title: Fabriquer ton interrupteur
    completion:
      - internal
  - 
    title: Questionnaire rapide
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Améliorer ton projet
  - 
    title: Et ensuite ?
